name: draw_cover
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  image_picker: ^0.6.3+4
  image_crop: ^0.3.2
  image_cropper: ^1.2.1
  #  file_picker: ^1.4.3+2
  universal_html: ^1.1.10
  matrix_gesture_detector: ^0.1.0
  vector_math: ^2.0.5
  sliding_up_panel: ^1.0.0
  #  carousel_slider: ^1.4.1
  photo: ^0.4.8
  #  permission_handler: ^5.0.0
  double_back_to_close_app: ^0.1.2
  shared_preferences: ^0.5.6+3
  flutter_launcher_icons: ^0.7.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app.png"

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/

  fonts:
    - family: Myriad
      fonts:
        - asset: assets/fonts/Myriad-Pro.ttf
        - asset: assets/fonts/Myriad-Pro.ttf
          style: italic